# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Confidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='EngineSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('epsilon', models.FloatField()),
                ('eta', models.FloatField()),
                ('M', models.FloatField()),
                ('r_star', models.FloatField()),
                ('L_star', models.FloatField()),
                ('W_p', models.FloatField()),
                ('W_r', models.FloatField()),
                ('W_c', models.FloatField()),
                ('W_d', models.FloatField()),
                ('slip_probability', models.FloatField()),
                ('guess_probability', models.FloatField()),
                ('trans_probability', models.FloatField()),
                ('prior_knowledge_probability', models.FloatField()),
                ('stop_on_mastery', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Exposure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mastery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('knowledge_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.KnowledgeComponent')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Learner')),
            ],
        ),
        migrations.CreateModel(
            name='PrerequisiteRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('knowledge_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.KnowledgeComponent')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_relation', to='engine.KnowledgeComponent')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Activity')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Learner')),
            ],
        ),
        migrations.CreateModel(
            name='Slip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Activity')),
                ('knowledge_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.KnowledgeComponent')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Activity')),
                ('knowledge_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.KnowledgeComponent')),
            ],
        ),
        migrations.AddField(
            model_name='guess',
            name='knowledge_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.KnowledgeComponent'),
        ),
        migrations.AddField(
            model_name='exposure',
            name='knowledge_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.KnowledgeComponent'),
        ),
        migrations.AddField(
            model_name='exposure',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Learner'),
        ),
        migrations.AddField(
            model_name='difficulty',
            name='knowledge_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.KnowledgeComponent'),
        ),
        migrations.AddField(
            model_name='confidence',
            name='knowledge_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.KnowledgeComponent'),
        ),
        migrations.AddField(
            model_name='confidence',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Learner'),
        ),
        migrations.AddField(
            model_name='activity',
            name='collections',
            field=models.ManyToManyField(to='engine.Collection'),
        ),
        migrations.AddField(
            model_name='activity',
            name='knowledge_components',
            field=models.ManyToManyField(blank=True, to='engine.KnowledgeComponent'),
        ),
    ]
