# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='collections',
        ),
        migrations.AddField(
            model_name='activity',
            name='collections',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='engine.Collection'),
            preserve_default=False,
        ),
    ]
