# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-08 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
