# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_auto_20170918_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='collections',
            new_name='collection',
        ),
    ]
