# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_auto_20170918_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='difficulty',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='difficulty',
            name='knowledge_component',
        ),
        migrations.RemoveField(
            model_name='learner',
            name='identifier',
        ),
        migrations.AddField(
            model_name='activity',
            name='difficulty',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='tags',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='Difficulty',
        ),
    ]
