# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-09 02:41
from __future__ import unicode_literals

from django.db import migrations

def make_many_collections(apps, schema_editor):
    """
    Adds the Collection object in Activity.collection to the
    many-to-many relationship in Activity.collections
    """
    Activity = apps.get_model('engine','Activity')
    for activity in Activity.objects.all():
        activity.collections.add(activity.collection)

class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_auto_20180209_0240'),
    ]

    operations = [
        migrations.RunPython(make_many_collections),
    ]
