# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-09 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_auto_20180209_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='collection',
        ),
        migrations.AlterField(
            model_name='activity',
            name='collections',
            field=models.ManyToManyField(blank=True, to='engine.Collection'),
        ),
    ]
