# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_auto_20170918_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='difficulty',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
