# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_auto_20170918_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgecomponent',
            name='mastery_prior',
            field=models.FloatField(default=0.2),
            preserve_default=False,
        ),
    ]
