# Generated by Django 2.0.5 on 2018-05-18 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_auto_20180513_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentalgroup',
            name='engine_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.EngineSettings'),
        ),
        migrations.AlterField(
            model_name='learner',
            name='experimental_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.ExperimentalGroup'),
        ),
    ]
