# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-13 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_auto_20180513_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='lti_user_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
