# Generated by Django 2.0.5 on 2018-05-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_auto_20180518_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='tool_consumer_instance_guid',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='learner',
            name='user_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='learner',
            unique_together={('user_id', 'tool_consumer_instance_guid')},
        ),
    ]
