# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_score_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(default='', max_length=200),
        ),
    ]
