# Generated by Django 2.0.5 on 2018-05-20 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_auto_20180519_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='experimental_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.ExperimentalGroup'),
        ),
    ]
