# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_activity_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transfer',
            new_name='Transit',
        ),
    ]
