# Generated by Django 2.0.5 on 2018-06-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0010_auto_20180603_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collection_id',
            field=models.CharField(max_length=200, null=True),
            preserve_default=False,
        ),
    ]
