# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0010_auto_20170922_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('weight', models.FloatField()),
                ('engine_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.EngineSettings')),
            ],
        ),
        migrations.AddField(
            model_name='learner',
            name='experimental_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='engine.ExperimentalGroup'),
            preserve_default=False,
        ),
    ]
