# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0011_auto_20170923_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentalgroup',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
