# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0012_auto_20170923_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='experimental_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.ExperimentalGroup'),
        ),
    ]
