# Generated by Django 2.0.5 on 2018-06-13 02:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0012_auto_20180613_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_id',
            field=models.CharField(max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
