# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0013_auto_20170923_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentalgroup',
            name='engine_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.EngineSettings'),
        ),
    ]
