# Generated by Django 2.0.5 on 2018-06-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0013_auto_20180613_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
