# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0014_auto_20170923_0326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='collection',
        ),
        migrations.AddField(
            model_name='activity',
            name='collection',
            field=models.ManyToManyField(to='engine.Collection'),
        ),
    ]
