# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0015_auto_20170925_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='collection',
        ),
        migrations.AddField(
            model_name='activity',
            name='collections',
            field=models.ManyToManyField(blank=True, to='engine.Collection'),
        ),
    ]
