# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0016_auto_20170925_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='collections',
        ),
        migrations.AddField(
            model_name='activity',
            name='collection',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='engine.Collection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='include_adaptive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
