# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0017_auto_20170926_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='max_problems',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
