# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0018_collection_max_problems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgecomponent',
            name='mastery_prior',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
