# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0019_auto_20170927_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='order',
            new_name='nonadaptive_order',
        ),
        migrations.AddField(
            model_name='activity',
            name='preadaptive_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
